"""Adding password, adding status

Revision ID: 69310ae656bd
Revises: e6bab5ba8ebb
Create Date: 2024-11-29 01:25:22.132157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69310ae656bd'
down_revision: Union[str, None] = 'e6bab5ba8ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('status', mysql.INTEGER(), nullable=False))
    op.add_column('tasks', sa.Column('status', sa.INTEGER(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('status', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'password')
    op.drop_column('tasks', 'status')
    op.drop_column('groups', 'status')
    # ### end Alembic commands ###
