"""Adding role

Revision ID: 7d77f955e52e
Revises: 43915dc9bdad
Create Date: 2024-11-28 21:16:02.256370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d77f955e52e'
down_revision: Union[str, None] = '43915dc9bdad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('role', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'role')
    # ### end Alembic commands ###
